name: LaTeX

on:
  - push:
  - workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true

      - name: Generate PNGs
        run: |
          sudo apt install poppler-utils
          pdftoppm -png cv.pdf cv

      - name: Check output
        run: ls

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cv.pdf
            cv-1.png
